### ISSUE TITLE
More info about the purpose and advantages

### ISSUE THREAD

**Issue by johanlahti** [qlik-oss/after-work.js#61]
### Description

Encountering after-work for the first time the first thing I want to know is how this tool facilitates my work. Especially, *why* I should choose after-work instead of e.g. writing a shell script executing the tests in desired order (unit, component, integration, end-to-end) – or using "established" tools like grunt and gulp (which might not even be a good comparison).

**Comment by stoffeastrom** [comment]
One of the main purposes of `after-work.js` is to streamline your testing environment. It sets up the environment by default with `mocha`, `sinon`, `sinon-chai` etc. Remember that this is used both for `node` and `browser` environments. So switching context should be easy as the same tools are used. One requirement when starting with `after-work.js` was that we should have has few dependencies as possible. Using `grunt` or `gulp` just adds an layer which we didn't want to have.

Also, in `next` version of `after-work.js` the focus has been to enhance the developer experience. Meaning that you should be able to debug your tests with a breeze. Since `phantomjs` is dead the upcoming star is chrome headless which gives us opportunities. Together with awesome editors it will be possible to debug the tests in your editor which should increase your productivity a lot.

Hope this gives you a bit more insight!

**Comment by johanlahti** [comment]
Thanks for the explanation! I think the tool can has a great potential of helping many more developers/companies setting up a complete test environment by touching only a few configs. This is exactly what should be emphasised on the Readme-page. Something like:

"Get your complete testing pyramid environment ready in just a few minutes. Click here to get started!"
1. Install
2. Write some test code
3. Run `after-work.js myFile.spec.js`
4. Beautiful feedback in browser

**Advantages**
- Easy to get started and to configure for your needs
- Works in node and browser
- All essential libraries included (mocha, sinon, sinon-chai)
- Extend with plugins
- Coming soon: debugging in browser…

And maybe some super-easy "Hello World"-examples in the very beginning of the Readme-page.

**Comment by stoffeastrom** [comment]
We now have multiple examples running which also runs on circle ci. 

https://aw.netlify.com/examples.html. Closing this. Thanks for the feedback
